// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/ai/chat": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "发送问题给 AI 助手获取回答",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI"
                ],
                "summary": "AI 问答",
                "parameters": [
                    {
                        "description": "问答请求",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.AIChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.AIChatResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/ai/quota": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取用户当日 AI 使用配额情况",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI"
                ],
                "summary": "获取 AI 配额",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.AIQuotaResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/ai/speech/recognize": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "将语音转为文字",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI"
                ],
                "summary": "语音识别",
                "parameters": [
                    {
                        "type": "file",
                        "description": "音频文件",
                        "name": "audio",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.SpeechRecognizeResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/device/register": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "注册设备 token，用于推送通知",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "推送"
                ],
                "summary": "注册推送设备",
                "parameters": [
                    {
                        "description": "设备信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.RegisterDeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/photo": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "分页获取指定宝宝的照片列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "照片"
                ],
                "summary": "获取照片列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "宝宝ID",
                        "name": "baby_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/model.ListResponse"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "list": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/handler.PhotoResponse"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/photo/callback": {
            "post": {
                "description": "OSS 上传完成后的回调处理",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "照片"
                ],
                "summary": "照片上传回调",
                "parameters": [
                    {
                        "description": "回调参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.PhotoCallbackRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/photo/upload-url": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取阿里云 OSS 直传签名 URL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "照片"
                ],
                "summary": "获取照片上传 URL",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.PhotoUploadURLRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.PhotoUploadURLResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/photo/{id}": {
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "删除指定照片",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "照片"
                ],
                "summary": "删除照片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "照片ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/record": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "分页获取指定宝宝的记录列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "记录"
                ],
                "summary": "获取记录列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "宝宝ID",
                        "name": "baby_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "记录类型: feeding/sleep/diaper/growth",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量，默认20",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/model.ListResponse"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "list": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/handler.RecordResponse"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "创建喂养/睡眠/排泄/成长记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "记录"
                ],
                "summary": "创建记录",
                "parameters": [
                    {
                        "description": "记录信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreateRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.RecordResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/record/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取指定记录的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "记录"
                ],
                "summary": "获取记录详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "记录ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.RecordDetailResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新指定记录的信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "记录"
                ],
                "summary": "更新记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "记录ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.RecordResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "删除指定记录（软删除）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "记录"
                ],
                "summary": "删除记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "记录ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/stats/daily": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取指定日期的喂养/睡眠/排泄统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "统计"
                ],
                "summary": "日统计",
                "parameters": [
                    {
                        "type": "string",
                        "description": "宝宝ID",
                        "name": "baby_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "日期(YYYY-MM-DD)",
                        "name": "date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.DailyStatsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/stats/weekly": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取近7天喂养/睡眠/排泄统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "统计"
                ],
                "summary": "周统计",
                "parameters": [
                    {
                        "type": "string",
                        "description": "宝宝ID",
                        "name": "baby_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.WeeklyStatsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/sync/stream": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "建立服务器发送事件连接，接收家庭数据变更",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "同步"
                ],
                "summary": "SSE 实时同步",
                "responses": {
                    "200": {
                        "description": "SSE 连接建立"
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.AIChatRequest": {
            "type": "object",
            "required": [
                "question"
            ],
            "properties": {
                "baby_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.ChatHistory"
                    }
                },
                "question": {
                    "type": "string",
                    "example": "宝宝三个月应该喝多少奶"
                }
            }
        },
        "handler.AIChatResponse": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "remaining_quota": {
                    "type": "integer"
                },
                "tokens_used": {
                    "type": "integer"
                }
            }
        },
        "handler.AIQuotaResponse": {
            "type": "object",
            "properties": {
                "ai_chat": {
                    "$ref": "#/definitions/handler.QuotaDetail"
                },
                "speech": {
                    "$ref": "#/definitions/handler.QuotaDetail"
                }
            }
        },
        "handler.ChatHistory": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "之前的问题"
                },
                "role": {
                    "type": "string",
                    "example": "user"
                }
            }
        },
        "handler.CreateRecordRequest": {
            "type": "object",
            "required": [
                "baby_id",
                "content",
                "started_at",
                "type"
            ],
            "properties": {
                "baby_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "content": {
                    "type": "object",
                    "additionalProperties": true
                },
                "ended_at": {
                    "type": "string",
                    "example": "2024-03-08T10:15:00Z"
                },
                "note": {
                    "type": "string",
                    "example": "备注信息"
                },
                "started_at": {
                    "type": "string",
                    "example": "2024-03-08T10:00:00Z"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "feeding",
                        "sleep",
                        "diaper",
                        "growth"
                    ],
                    "example": "feeding"
                }
            }
        },
        "handler.DailyStatsResponse": {
            "type": "object",
            "properties": {
                "diaper": {
                    "$ref": "#/definitions/handler.DiaperStats"
                },
                "feeding": {
                    "$ref": "#/definitions/handler.FeedingStats"
                },
                "sleep": {
                    "$ref": "#/definitions/handler.SleepStats"
                }
            }
        },
        "handler.DiaperStats": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                }
            }
        },
        "handler.FeedingStats": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "total_amount": {
                    "type": "integer"
                }
            }
        },
        "handler.PhotoCallbackRequest": {
            "type": "object",
            "required": [
                "etag",
                "photo_id",
                "size"
            ],
            "properties": {
                "etag": {
                    "type": "string"
                },
                "photo_id": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "handler.PhotoResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "taken_at": {
                    "type": "string"
                },
                "thumb_url": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "handler.PhotoUploadURLRequest": {
            "type": "object",
            "required": [
                "baby_id",
                "content_type",
                "filename",
                "size"
            ],
            "properties": {
                "baby_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "content_type": {
                    "type": "string",
                    "example": "image/jpeg"
                },
                "filename": {
                    "type": "string",
                    "example": "photo.jpg"
                },
                "size": {
                    "type": "integer",
                    "example": 2048000
                }
            }
        },
        "handler.PhotoUploadURLResponse": {
            "type": "object",
            "properties": {
                "access_url": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "integer"
                },
                "form_data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "photo_id": {
                    "type": "string"
                },
                "thumb_url": {
                    "type": "string"
                },
                "upload_url": {
                    "type": "string"
                }
            }
        },
        "handler.QuotaDetail": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "remaining": {
                    "type": "integer"
                },
                "used": {
                    "type": "integer"
                }
            }
        },
        "handler.RecordDetailResponse": {
            "type": "object",
            "properties": {
                "baby_id": {
                    "type": "string"
                },
                "content": {
                    "type": "object",
                    "additionalProperties": true
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "ended_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "handler.RecordResponse": {
            "type": "object",
            "properties": {
                "baby_id": {
                    "type": "string"
                },
                "content": {
                    "type": "object",
                    "additionalProperties": true
                },
                "duration_hours": {
                    "description": "睡眠记录时长（小时）",
                    "type": "number"
                },
                "ended_at": {
                    "type": "string"
                },
                "hours_since_last_feed": {
                    "description": "喂养记录的间隔小时数（无上一次记录时为空）",
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "handler.RegisterDeviceRequest": {
            "type": "object",
            "required": [
                "device_token",
                "platform"
            ],
            "properties": {
                "alias": {
                    "type": "string"
                },
                "device_token": {
                    "type": "string"
                },
                "platform": {
                    "type": "string",
                    "enum": [
                        "ios",
                        "android"
                    ]
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handler.SleepStats": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "total_hours": {
                    "type": "number"
                }
            }
        },
        "handler.SpeechRecognizeResponse": {
            "type": "object",
            "properties": {
                "confidence": {
                    "type": "number"
                },
                "remaining_quota": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "handler.UpdateRecordRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "object",
                    "additionalProperties": true
                },
                "ended_at": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                }
            }
        },
        "handler.WeeklyStatsResponse": {
            "type": "object",
            "properties": {
                "dates": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "diaper": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "feeding": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "sleep": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                }
            }
        },
        "model.ListResponse": {
            "type": "object",
            "properties": {
                "list": {},
                "pagination": {
                    "$ref": "#/definitions/model.Pagination"
                }
            }
        },
        "model.Pagination": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "model.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Yuanzi API",
	Description:      "小园子母婴记录应用后端 API (基于 PRD-V1.1)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
